"""add is_onboarded to users

Revision ID: f0224fe50b45
Revises: a5512b7d82f4
Create Date: 2026-05-01 12:55:53.654076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0224fe50b45'
down_revision: Union[str, Sequence[str], None] = 'a5512b7d82f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###
